AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - "db/schema.rb"
  UseCache: false
Rails:
  Enabled: true
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/Documentation:
  Enabled: false
Lint/AmbiguousOperator:
  Enabled: false
Style/TrailingBlankLines:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Lint/Eval:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/SpaceBeforeBlockBraces:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/EmptyElse:
  Enabled: false
Style/SpaceInsideBlockBraces:
  Enabled: false
Lint/Debugger:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Rails/FindEach:
  Enabled: false
Style/Next:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/EmptyLinesAroundMethodBody:
  Enabled: false
Lint/UnusedBlockArgument:
  Enabled: false
Style/MethodCallParentheses:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  Enabled: false
Style/Proc:
  Enabled: false
Style/DotPosition:
  Enabled: false
Style/MultilineMethodCallIndentation:
  Enabled: false
Style/Lambda:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/ExtraSpacing:
  Enabled: false
Lint/UnderscorePrefixedVariableName:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/IndentHash:
  Enabled: false
Style/EmptyLines:
  Enabled: false
Lint/LiteralInCondition:
  Enabled: false
Style/MultilineHashBraceLayout:
  Enabled: false
Lint/EndAlignment:
  Enabled: false
Style/ElseAlignment:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/MultilineMethodCallBraceLayout:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/IndentationWidth:
  Enabled: false
