default: &default
  database: <%= "lumumba_#{ENV['RAILS_ENV'] || ENV['RACK_ENV'] || Rails.env}" %>
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  port: 5432

development:
  <<: *default

test:
  <<: *default

rds: &rds
  user: root
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOST'] %>

production:
  <<: *default
  <<: *rds

staging:
  <<: *default
  <<: *rds
