common: &common
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
  stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>

development:
  <<: *common
  secret_key_base: 3fa5ba949f88d1d1a2e47d6f666e8761696ad370c00f2a078c38a7ca25d09790a0dda846cf09398bf7d4a58adfec62989b74528203c8636b8783a51870bf3734

test:
  <<: *common
  secret_key_base: 6848b389075454a775efafe02cc9ad70bfe3ca33c6f11a7a797c065ea3628cdbf0de8febdec75d60c709eed446c366bd0c0df7b069d3f995eedbdbfb56693666

production:
  <<: *common
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  <<: *common
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
